### ISSUE TITLE
IOException when closing a survey

### ISSUE THREAD

**Issue by gumil** [Survicate/survicate-android-sdk#11]
```
Survicate Sdk Exception: 
    java.lang.IllegalStateException: Error occurred during the synchronisation of surveys` `closed` status.
        at com.survicate.surveys.SynchronizationManager$13.accept(SynchronizationManager.java:220)
        at com.survicate.surveys.SynchronizationManager$13.accept(SynchronizationManager.java:217)
        at com.survicate.surveys.utils.SimpleAsyncTask$1.doInBackground(SimpleAsyncTask.java:63)
        at com.survicate.surveys.utils.SimpleAsyncTask$1.doInBackground(SimpleAsyncTask.java:55)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.IOException: HTTP error code: 400
        at com.survicate.surveys.infrastructure.network.HttpsSurvicateApi.loadUrlResponse(HttpsSurvicateApi.java:95)
        at com.survicate.surveys.infrastructure.network.HttpsSurvicateApi.sendSurveyClosedEvent(HttpsSurvicateApi.java:62)
        at com.survicate.surveys.SynchronizationManager$14.call(SynchronizationManager.java:199)
        at com.survicate.surveys.SynchronizationManager$14.call(SynchronizationManager.java:193)
        at com.survicate.surveys.utils.SimpleAsyncTask$1.doInBackground(SimpleAsyncTask.java:60)
        at com.survicate.surveys.utils.SimpleAsyncTask$1.doInBackground(SimpleAsyncTask.java:55) 
        at android.os.AsyncTask$3.call(AsyncTask.java:378) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

Should we be worried about this exception? It happens when you close a survey using the close button.

**Comment by j-brzozowski** [comment]
It should be fixed in 1.1.2. Please update SDK version.
